application: active-cloud-db-go
version: 1
runtime: go
api_version: 1

handlers:
- url: /static/js/custom.js
  static_files: static/js/custom.js
  upload: static/js/custom.js

- url: /.*
  script: _go_app

