application: active-cloud-db-go
version: 1
runtime: go
api_version: 2

handlers:
- url: /static/css/bootstrap-1.1.0.min.css
  static_files: static/css/bootstrap-1.1.0.min.css
  upload: static/css/bootstrap-1.1.0.min.css

- url: /static/img/Golang.png
  static_files: static/img/Golang.png
  upload: static/img/Golang.png

- url: /static/img/appengine-silver-120x30.gif
  static_files: static/img/appengine-silver-120x30.gif
  upload: static/img/appengine-silver-120x30.gif

- url: /static/js/jquery.js
  static_files: static/js/jquery.min.js
  upload: static/js/jquery.min.js

- url: /static/js/jquery.tablesorter.min.js
  static_files: static/js/jquery.tablesorter.min.js
  upload: static/js/jquery.tablesorter.min.js

- url: /static/js/custom.js
  static_files: static/js/custom.js
  upload: static/js/custom.js

- url: /.*
  script: _go_app

